= Camunda BPM Spring Boot Starter Reference Guide

== What is camunda-bpm-spring-boot-starter?

== Getting started

If you are not familiar with link:http://projects.spring.io/spring-boot/[Spring Boot^] read the reference documentation link:http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started[getting started^] guide.

To enable camunda bpm auto configuration add the following dependency:

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
  <groupId>org.camunda.bpm.extension</groupId>
  <artifactId>camunda-bpm-spring-boot-starter</artifactId>
  <version>{project-version}</version>
</dependency>
----

This will add the camunda version `{camunda-version}` to your dependencies. If you want to override the version add `camunda.version` property with the camunda version you want to use and add the camunda bom to the dependency management:
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<properties>
  <camunda.version>{camunda-version}</camunda.version>
</properties>

<dependencyManagement>
  <dependencies>
    <dependency>
      <!-- Import dependency management from camunda -->
      <groupId>org.camunda.bpm</groupId>
      <artifactId>camunda-bom</artifactId>
      <version>${camunda.version}</version
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>

----

== Process engine configuration
The auto starter automatically applies all beans implementing the `org.camunda.bpm.spring.boot.starter.configuration.CamundaConfiguration` interface to configure the engine.

The configuration is divided into _sections_. These _sections_ are represented by the marker interfaces:

* `org.camunda.bpm.spring.boot.starter.configuration.CamundaProcessEngineConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaDatasourceConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaHistoryConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaJobConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaDeploymentConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaJpaConfiguration`

=== Default configurations

The following default and best practice configurations are provided by the starter and can be customized or overridden if you like to.

==== `DefaultProcessEngineConfiguration`

Sets the process engine name and automatically adds all `ProcessEnginePlugin` beans to the configuration.

==== `DefaultDatasourceConfiguration`

Applies the datasource and transaction management configurations to the process engine.
If you want to link:http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources[configure more than one datasource^] and don't want to use the `@Primary` one for the process engine then name the one you want to use as `camundaBpmDataSource`.

[source,java]
----
@Bean
@Primary
@ConfigurationProperties(prefix="datasource.primary")
public DataSource primaryDataSource() {
  return DataSourceBuilder.create().build();
}

@Bean(name="camundaBpmDataSource")
@ConfigurationProperties(prefix="datasource.secondary")
public DataSource secondaryDataSource() {
  return DataSourceBuilder.create().build();
}
----

==== `DefaultHistoryConfiguration`

Applies the history configuration to the process engine. If not configured the `camunda` default level will be used.
If you want to use a custom `HistoryEventHandler` you just have to provide a bean implementing the interface.
[source,java]
----
@Bean
public HistoryEventHandler customHistoryEventHandler() {
  return new CustomHistoryEventHanlder();
}
----

==== `DefaultJobConfiguration`

Applies the job execution properties to the process engine.

To have more control about the execution itself you can provide your own

- `org.camunda.bpm.engine.impl.jobexecutor.JobExecutor`
- `org.springframework.core.task.TaskExecutor`

beans.

IMPORTANT: The job executor is not enabled in the configuration.
This is done after the spring context successfully loaded (see `org.camunda.bpm.spring.boot.starter.runlistener`).

==== `DefaultDeploymentConfiguration`

If auto deployment is enabled (this is by default) all process found in the classpath will be deployed.
The resource pattern can be changed using properties (see <<properties>>).

==== `DefaultJpaConfiguration`

If JPA is enabled and a `entityManagerFactory` bean is configured the process engine will be enabled to use JPA (see <<properties>>).

=== Overriding a default configuration

Provide a bean implementing one of the marker interfaces. For example to customize the datasource configuration:

[source,java]
----
@Configuration
public class MyCamundaConfiguration {

	@Bean
	public static CamundaDatasourceConfiguration camundaDatasourceConfiguration() {
		return new MyCamundaDatasourceConfiguration();
	}

}
----

=== Adding additional configurations

You just have to provide one or more beans implementing the `org.camunda.bpm.spring.boot.starter.configuration.CamundaConfiguration` interface. The configurations are applied ordered using the spring ordering mechanism (`@Order` annotation and `Ordered` interface). So if you want that your configuration is applied before the default configurations add a `@Order(CamundaConfiguration.DEFAULT_ORDER - 1)` annotation to your class. If you want that your configuration is applied after the default configurations add a `@Order(CamundaConfiguration.DEFAULT_ORDER + 1)` annotation to your class.

[source,java]
----
@Configuration
public class MyCamundaConfiguration {

	@Bean
	@Order(CamundaConfiguration.DEFAULT_ORDER + 1)
	public static CamundaConfiguration myCustomConfiguration() {
		return new MyCustomConfiguration();
	}

}
----

Or if you have component scan enabled:

[source,java]
----
@Component
@Order(CamundaConfiguration.DEFAULT_ORDER + 1)
public class MyCustomConfiguration implements CamundaConfiguration {

	@Override
	public void apply(SpringProcessEngineConfiguration configuration) {
		//...
	}

}
----

[[properties]]
== Camunda application properties
[options="header"]
|===
|Property name |Description | Default value
|`{properties-prefix}.process-engine-name`
|name of the process engine
|camunda default value

|`{properties-prefix}.job-execution.active`
|activate job execution after successful startup
|`true`

|`{properties-prefix}.job-execution.deployment-aware`
|if job executor is deployment aware
|`false`

|`{properties-prefix}.database.schema-update`
|if automatic schema update should be applied
|`true`

|`{properties-prefix}.database.type`
|type of the underlying database
|

|`{properties-prefix}.database.table-prefix`
|prefix of the camunda database tables
|camunda default value

|`{properties-prefix}.history-level`
|camunda history level
|camunda default value

|`{properties-prefix}.auto-deployment-enabled`
|if processes should be auto deployed
|`true`

|`{properties-prefix}.deployment-resource-pattern`
|location for auto deployment
|`classpath*:**/*.bpmn`

|`{properties-prefix}.jpa.enabled`
|enables jpa configuration
|`true`. Depends on `entityManagerFactory` bean.

|`{properties-prefix}.jpa-persistence-unit-name`
|JPA persistence unit name
|

|`{properties-prefix}.jpa.close-entity-manager`
|close JPA entity manager
|`true`

|`{properties-prefix}.jpa.handle-transaction`
|JPA handle transaction
|`true`

|`management.health.camunda.enabled`
|enables default camunda health indicators
|`true`

|`camunda.bpm.rest.enabled`
|enables camunda rest services
|`true`
|===
