= Camunda BPM Spring Boot Starter Reference Guide

== What is camunda-bpm-spring-boot-starter?

== Getting started

If you are not familiar with link:http://projects.spring.io/spring-boot/[Spring Boot^] read the reference documentation link:http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started[getting started^] guide.

To enable camunda bpm auto configuration add the following dependency:

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
  <groupId>org.camunda.bpm.extension</groupId>
  <artifactId>camunda-bpm-spring-boot-starter</artifactId>
  <version>{project-version}</version>
</dependency>
----

This will add the camunda version `{camunda-version}` to your dependencies. If you want to override the version add `camunda.version` property with the camunda version you want to use and add the camunda bom to the dependency management:
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<properties>
  <camunda.version>{camunda-version}</camunda.version>
</properties>

<dependencyManagement>
  <dependencies>
    <dependency>
      <!-- Import dependency management from camunda -->
      <groupId>org.camunda.bpm</groupId>
      <artifactId>camunda-bom</artifactId>
      <version>${camunda.version}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>

----

== Process engine configuration
The auto starter uses the  `org.camunda.bpm.engine.impl.cfg.ProcessEnginePlugin` mechanism to configure the engine.

The configuration is divided into _sections_. These _sections_ are represented by the marker interfaces:

* `org.camunda.bpm.spring.boot.starter.configuration.CamundaProcessEngineConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaDatasourceConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaHistoryConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaHistoryLevelAutoHandlingConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaJobConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaDeploymentConfiguration`
* `org.camunda.bpm.spring.boot.starter.configuration.CamundaJpaConfiguration`

=== Default configurations

The following default and best practice configurations are provided by the starter and can be customized or overridden if you like to.

==== `DefaultProcessEngineConfiguration`

Sets the process engine name and automatically adds all `ProcessEnginePlugin` beans to the configuration.

==== `DefaultDatasourceConfiguration`

Applies the datasource and transaction management configurations to the process engine.
If you want to link:http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources[configure more than one datasource^] and don't want to use the `@Primary` one for the process engine then name the one you want to use as `camundaBpmDataSource`.

[source,java]
----
@Bean
@Primary
@ConfigurationProperties(prefix="datasource.primary")
public DataSource primaryDataSource() {
  return DataSourceBuilder.create().build();
}

@Bean(name="camundaBpmDataSource")
@ConfigurationProperties(prefix="datasource.secondary")
public DataSource secondaryDataSource() {
  return DataSourceBuilder.create().build();
}
----

IMPORTANT: When using `history-level auto` with more then one database and camunda version < 7.4 you have to provide a `JdbcTemplate` bean as `camundaBpmJdbcTemplate` corresponding to the `camundaBpmDataSource`.

==== `DefaultHistoryConfiguration`

Applies the history configuration to the process engine. If not configured the `camunda` default level will be used.
If you want to use a custom `HistoryEventHandler` you just have to provide a bean implementing the interface.
[source,java]
----
@Bean
public HistoryEventHandler customHistoryEventHandler() {
  return new CustomHistoryEventHanlder();
}
----

==== `DefaultHistoryLevelAutoHandlingConfiguration`
As camunda version >= 7.4 supports `history-level auto` this configuration adds support for versions < = 7.3.

To have more control about the handling you can provide your own

- `org.camunda.bpm.spring.boot.starter.jdbc.HistoryLevelDeterminator` with name `historyLevelDeterminator`

IMPORTANT: The default configuration is applied after all other default configurations using the ordering mechanism.

==== `DefaultJobConfiguration`

Applies the job execution properties to the process engine.

To have more control about the execution itself you can provide your own

- `org.camunda.bpm.engine.impl.jobexecutor.JobExecutor`
- `org.springframework.core.task.TaskExecutor`

beans.

IMPORTANT: The job executor is not enabled in the configuration.
This is done after the spring context successfully loaded (see `org.camunda.bpm.spring.boot.starter.runlistener`).

==== `DefaultDeploymentConfiguration`

If auto deployment is enabled (this is by default) all process found in the classpath will be deployed.
The resource pattern can be changed using properties (see <<properties>>).

==== `DefaultJpaConfiguration`

If JPA is enabled and a `entityManagerFactory` bean is configured the process engine will be enabled to use JPA (see <<properties>>).

=== Overriding a default configuration

Provide a bean implementing one of the marker interfaces. For example to customize the datasource configuration:

[source,java]
----
@Configuration
public class MyCamundaConfiguration {

	@Bean
	public static CamundaDatasourceConfiguration camundaDatasourceConfiguration() {
		return new MyCamundaDatasourceConfiguration();
	}

}
----

=== Adding additional configurations

You just have to provide one or more beans implementing the `org.camunda.bpm.engine.impl.cfg.ProcessEnginePlugin` interface (or extend from `org.camunda.bpm.spring.boot.starter.configuration.impl.AbstractCamundaConfiguration`). The configurations are applied ordered using the spring ordering mechanism (`@Order` annotation and `Ordered` interface). So if you want that your configuration is applied before the default configurations add a `@Order(Ordering.DEFAULT_ORDER - 1)` annotation to your class. If you want that your configuration is applied after the default configurations add a `@Order(Ordering.DEFAULT_ORDER + 1)` annotation to your class.

[source,java]
----
@Configuration
public class MyCamundaConfiguration {

	@Bean
	@Order(Ordering.DEFAULT_ORDER + 1)
	public static ProcessEnginePlugin myCustomConfiguration() {
		return new MyCustomConfiguration();
	}

}
----

Or if you have component scan enabled:

[source,java]
----
@Component
@Order(Ordering.DEFAULT_ORDER + 1)
public class MyCustomConfiguration implements ProcessEnginePlugin {

	@Override
	public void preInit(ProcessEngineConfigurationImpl processEngineConfiguration) {
		//...
	}
	
	...

}
----

or

[source,java]
----
@Component
@Order(Ordering.DEFAULT_ORDER + 1)
public class MyCustomConfiguration extends AbstractCamundaConfiguration {

	@Override
	public void preInit(SpringProcessEngineConfiguration springProcessEngineConfiguration) {
		//...
	}
	
	...

}
----

== REST API

To enable link:https://docs.camunda.org/manual/7.5/reference/rest/[REST API^] you can use

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
  <groupId>org.camunda.bpm.extension</groupId>
  <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
  <version>{project-version}</version>
</dependency>
----

By default the application path is `rest`.

Because we are using jersey one can use spring boot's link:http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[common application properties]. For example to change the application path use `spring.jersey.application-path=myapplicationpath`.

To modify the configuration or register additional resources one can provide a bean which extends from `org.camunda.bpm.spring.boot.starter.rest.CamundaJerseyResourceConfig`:

[source,java]
----
@Component
@ApplicationPath("/rest")
public class JerseyConfig extends CamundaJerseyResourceConfig {

  @Override
  protected void registerAdditionalResources() {
    register(...);
  }

}
----

== Web Applications

To enable link:https://docs.camunda.org/manual/7.4/webapps/[Web Applications^]
(Admin, Cockpit and Tasklist for now) you can use

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
  <groupId>org.camunda.bpm.extension</groupId>
  <artifactId>camunda-bpm-spring-boot-starter-webapp</artifactId>
  <version>{project-version}</version>
</dependency>
----

IMPORTANT: This feature depends on camunda bpm version >= 7.4!

By default the starter registers a controller to redirect `/` to camundas bundled `index.html`.
To disable this you have to add `camunda.bpm.webapp.index-redirect-enabled=false` to your application properties.

The default camunda URLs are:
[options="header"]
|===
|Webapp|URL
|default|http://localhost:8080
|admin|http://localhost:8080/app/admin/index.html
|tasklist|http://localhost:8080/app/tasklist/index.html
|cockpit|http://localhost:8080/app/cockpit/index.html
|===

== Using the ProcessApplication

By default, the camunda-spring-boot-starter is configured to use the SpringProcessEngineConfiguration auto deployment feature.
Since 1.2.0 you also have the possibility to do so via SpringBootProcessApplication. This disables the SpringProcessEngineConfiguration
auto-deploy feature and instead uses the required "META-INF/processes.xml"  as an indicator for resource scanning.
This also allows all processes.xml configuration features described here.

To use it, extend the ProcessApplication with your main application class:

[source,java]
----
@SpringBootApplication
public class MyApplication extends SpringBootProcessApplication{

...

}
----

include::properties.adoc[]
